### ISSUE TITLE
How to use the refreshtoken to get a new accesstoken?

### ISSUE THREAD

**Issue by Rainer-Lang** [bkiers/retrofit-oauth#1]

**Comment by bkiers** [comment]
Hey Rainer, I included an example how to use the `refresh_token` in the [Main](https://github.com/bkiers/retrofit-oauth/blob/master/src/main/java/nl/bigo/retrofitoauth/Main.java) class.

**Comment by Rainer-Lang** [comment]
@bkiers Thanks. :-)

**Comment by bkiers** [comment]
You're welcome @Rainer-Lang
